server:
  port: 8001

spring:
  redis:
    database: 0
    host: 3.99.126.42
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3307/knowledge-planet-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root

# 在dev环境开启mybatis日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

website:
  domain-name: knowledgeplanet.art

# 定义freemarker生成的html位置
freemarker:
  html:
    target: ~/workspace/freemarker_html
    article: /Users/ethan/Documents/New\ Grad/Project/apache-tomcat-9.0.62/webapps/knowledgeplanet/portal/a