server:
  port: 8003

spring:
  redis:
    database: 0
    host: 3.99.126.42
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3307/knowledge-planet-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    #password: null

# 在dev环境开启mybatis日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

website:
  domain-name: knowledgeplanet.art